
name: CI
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: solve conflict
        run: |
          git clone --shallow-since=2023-07-20 https://github.com/nightshadow92/anime-offline-database.git
          cd anime-offline-database
          git checkout -b manami-project-master master
          git pull --shallow-since=2023-07-20 https://github.com/manami-project/anime-offline-database.git master
          git checkout --ours README.md
          git checkout master
          git merge --no-ff manami-project-master
          git push origin master
